class AddLoanuserDetailsToUser < ActiveRecord::Migration[6.0]
  def change
    add_column :users, :high_edu_level, :string
    add_column :users, :graduated_in, :date
    add_column :users, :marital_status, :string
    add_column :users, :children, :boolean
    add_column :users, :child_dependent, :boolean
    add_column :users, :live_in, :string
    add_column :users, :res_com, :boolean
    add_column :users, :com_addr_1, :string
    add_column :users, :com_addr_2, :string
    add_column :users, :com_zip, :string
    add_column :users, :com_city, :string
    add_column :users, :string, :string
    add_column :users, :com_state, :string
    add_column :users, :employed, :boolean
    add_column :users, :employment_type, :string
    add_column :users, :postion, :string
    add_column :users, :emp_from, :date
    add_column :users, :emp_to, :date
    add_column :users, :org_addr_1, :string
    add_column :users, :org_addr_2, :string
    add_column :users, :org_zip, :string
    add_column :users, :org_city, :string
    add_column :users, :org_state, :string
    add_column :users, :past_employment_type, :string
    add_column :users, :past_postion, :string
    add_column :users, :past_emp_from, :date
    add_column :users, :past_emp_to, :date
    add_column :users, :past_org_addr_1, :string
    add_column :users, :past_org_addr_2, :string
    add_column :users, :past_org_zip, :string
    add_column :users, :past_org_city, :string
    add_column :users, :past_org_state, :string
    add_column :users, :base_income, :float
    add_column :users, :overtime_income, :float
    add_column :users, :bonuses, :float
    add_column :users, :commissions, :float
    add_column :users, :divident_interest_income, :float
    add_column :users, :net_rental_income, :float
    add_column :users, :other_income, :float
    add_column :users, :housing_expense, :float
    add_column :users, :rent_expense, :float
    add_column :users, :first_mortgage, :string
    add_column :users, :other_fin_expense, :float
    add_column :users, :hazard_insur_exp, :float
    add_column :users, :real_estate_tax_exp, :float
    add_column :users, :mort_ins_exp, :float
    add_column :users, :hoa, :float
    add_column :users, :child_care_exp, :float
    add_column :users, :union_due_exp, :float
    add_column :users, :other_exp, :float
    add_column :users, :bank_assets, :float
    add_column :users, :credit_uni_assets, :float
    add_column :users, :stock_value, :float
    add_column :users, :bonds_value, :float
    add_column :users, :lic, :float
    add_column :users, :real_estate_owned, :float
    add_column :users, :vested_int_assests, :float
    add_column :users, :retirement_fund, :float
    add_column :users, :networth_of_business, :float
    add_column :users, :other_liquid, :float
    add_column :users, :other_nonliquid, :float
    add_column :users, :alimony_liability, :float
    add_column :users, :child_support_liability, :float
  end
end
